### ISSUE TITLE
Cannot Join Slack Channel (Broken Link)

### ISSUE THREAD

**Issue by OliverEvans96** [openfarmcc/OpenFarm#1279]
Hi there,

Seems like a really cool project, and I'd love to chat about it! Unfortunately, the [slack invitation link](https://slack.openfarm.cc) isn't working for me:

![image](https://user-images.githubusercontent.com/15915043/88745639-8e987d80-d118-11ea-98b9-259a88572f0e.png)

I'd love to hear when it's back up or if there's any temporary workaround.

Thanks,
Oliver

**Comment by OliverEvans96** [comment]
Specifically, it seems that the page is using a wildcard cert for `*.herokuapp.com` rather than `slack.openfarm.cc`

**Comment by nihonjinrxs** [comment]
@simonv3 @sophiakc you all seem to have been maintainers here in the past. Is the project still alive? If so, can you provide information on how to join Slack? Thanks!

**Comment by simonv3** [comment]
I don't think the Slack is still active. I haven't logged into it in like 5 years :P

**Comment by asbjornstokka** [comment]
Could Discord be a possibility, given that the slack is not active/alive? Been working on a LED-light/plant-sensor hobby project (IoT/OpenThread) for a while, and am just about to start growing plants, and would love to have a community.

**Comment by nihonjinrxs** [comment]
@asbjornstokka I'd be happy to join a Discord server for this if Slack is inactive.

(Below updated after digging further into the repo.)
I guess my question is what's happening with this project? It looks like a great amount of work happened here in the past, and there was a pretty solid community around it. When I looked prior, it seemed no updates had been made in a while. Now, it seems there's a PR that has been merged last May. So with that in mind, what do you see as the future of this project?
- Who is currently responsible for the maintenance of it? (Is that you @RickCarlino ?)
- Is there still a community around the project, and how might one get involved?
- Are you looking to hand it off to an interested party to maintain, or for help maintaining it? (I'd be interested if that's a possibility.)
- If not, is it possible for an interested party to get access to the database, fork it, and start something else with the data?

**Comment by asbjornstokka** [comment]
I first found openfarm through kickstarter a long time ago, and now searched it up again as I am creating an indoor LED plant light/sensors system going to grow myself herbs, strawberries etc, and also have some interested friends. I do lack in the plant knowledge, and thought I could most likely learn a lot here to avoid small mistakes, and hoped to find a community with people interested in plants and growing. From some of the PRs it seemed it was often updates of other modules?

**Comment by RickCarlino** [comment]
:wave: Hi, @nihonjinrxs @asbjornstokka .

I am going to ping @roryaronson about this matter, since I was not involved in the creation or management of the Slack channel.

To answer your question, I would call myself somewhat of an "interim lead developer". I wrote the vast majority of the codebase circa 2014. It was then handed off to a developer who took the role of lead. After he stepped down a few years ago, I picked things back up. After taking over for the second time, I became less active than the first time. The main reason is that my other project, FarmBot, is now a full-time job (it was just a side project years ago) and I also have a much different personal situation that doesn't afford me the same amount of time that I head back then.

OpenFarm is *not* a dead project, but development has undeniably stalled in recent years. We use the OpenFarm API every day at FarmBot. It is the knowledge database that we use for crops. I have not done a lot in terms of new feature development, but I do check in regularly to do things like database backups, security updates, deployment, etc.. If you have technical questions, I would be the best person to contact (see my GH profile for ways to contact me).

There is no urgent need to hand the project off (because stagnant != dead), but if a developer were interested in taking an active role in its development, I would be happy to help you however I can (explaining the software architecture, giving historical context on the app, etc..).

Please let me know if you have any questions. I will defer to @roryaronson about the Slack channel matters.

**Comment by nihonjinrxs** [comment]
Thanks for this context @RickCarlino ! I'm definitely interested in helping out, and I have a student who is also very interested, so I will try to contact you regarding that shortly.

I'll note that I tried to create an account and couldn't complete the process because of a certificate issue coupled with HSTS that prevents being able to confirm the email address. While not a dire consequence (I still seem to have an account and can log in), things like that make a project _appear_ dead and are generally worth fixing in my opinion. I'd be happy to help with that sort of thing too.

@roryaronson any information you can provide about getting involved in the community would be very welcome! Thanks!

**Comment by roryaronson** [comment]
As has been mentioned, the Slack group has not been active for quite some time, though it does still exist! There may be members in there open to discussion :) You can get get an automated invite link from here: https://openfarm-slack.herokuapp.com/ It looks like something with SSL lapsed with the slack.openfarm.cc subdomain, so that will no longer work unfortunately.
