### ISSUE TITLE
Pull policy logic out of show in the garden crop controller and into the relevant mutations. 

### ISSUE THREAD

**Issue by simonv3** [openfarmcc/OpenFarm#306]
@rickcarlino says: 

> If it works now, let's just ship it, but this logic probably could've gone into a mutation since there is branched logic going on and a couple of places where an API user might make a formatting error.

> It would also keep our API error format consistent, which will be useful for things like front end flash alerts.

[here](https://github.com/FarmBot/OpenFarm/pull/290/files#r20007041).

This isn't just happening in the garden crop controller but also in a couple of other places.

Places:
* [ ] `api/users_controller`
* [ ] `api/gardens_controller`
* [ ] `api/garden_crops_controller`

**Comment by simonv3** [comment]
test comment

**Comment by simonv3** [comment]
@RickCarlino does it make sense to put "view" logic (for show/index) in a mutation since nothing is being changed?

**Comment by RickCarlino** [comment]
@simonv3 Looks like things have changed quite a bit since I made that comment. I *think* (but can't confirm) that this was probably related to having authorization logic in a controller at the time. If you are using Pundit now, that should be good enough to get the job done. I think it looks pretty good since all the auth logic is composed elsewhere.

**Comment by simonv3** [comment]
That's what I figured. I didn't dig too deep into when you had made the comment, but looking at the files it seemed okay to me. Thanks for checking in on it!
