### ISSUE TITLE
Get our docker file up to speed

### ISSUE THREAD

**Issue by simonv3** [openfarmcc/OpenFarm#563]
@dnephin, you added it a while ago, did you get anywhere further with it. 

@guitsaru was saying he had some issues with getting ElasticSearch running in it. Since that's the main stumbling block for a lot of new developers to OF, that would be the ideal fix.

I'll try to see if I can get it running in the next week or so myself.

**Comment by dnephin** [comment]
Should be no problem to add elasticsearch, I'll get a PR out sometime this weekend

**Comment by simonv3** [comment]
@dnephin, that would be fantastic. Thanks you so much!

**Comment by md5** [comment]
I actually had a branch of this working locally about a week ago. I got held up with the CLA, but I'll get that sorted out now.

**Comment by dnephin** [comment]
Cool, [the branch](https://github.com/openfarmcc/OpenFarm/compare/master...md5:update-docker-setup) lgtm

There's some nice things you can do with creating indexes and installing plugins during the "build" (instead of doing it when the container is started), something [like this](https://github.com/dnephin/readthedocs.org/blob/docker_compose/readthedocs/search/Dockerfile), but it's easy enough to add that later.
