### ISSUE TITLE
Member Profile Pages

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#586]
I'm trying to make something like this over here: https://github.com/roryaronson/OpenFarm/tree/member-profiles

@simonv3 I scaffolded some of it and copy-pasted the `guides.index` into it and then the links to the Guides no longer worked. I fidgeted and added `@user` in front of `.guides.each` to make it work as much as it does. Not sure if that is the right thing to do. If you have a chance to check it out, that would be rad. I'm checking out for the weekend but am excited to pick this up again on Monday!

![member profile 2](https://cloud.githubusercontent.com/assets/5524043/6981618/825abe68-d9b9-11e4-9282-641674c34818.jpg)

**Comment by simonv3** [comment]
Hey Rory, I'll check this out tomorrow.

**Comment by simonv3** [comment]
This looks good! I would put the guides listing (`guides/index`) in the user folder, cause it's relevant to that view, not to the guides view (unless you want it to be shared, in which case you should put it in a shared folder). I would also consider breaking out a couple more of the sub-sections so that the show page doesn't become overwhelmingly large.

**Comment by roryaronson** [comment]
What is the problem with breaking `/guides` if it being moved to the member's profile page? Are you think people might have linked to it?

**Comment by simonv3** [comment]
Well, ideally we shouldn't break a URL because our folder organization doesn't follow standard Rails functionality.

I doubt people have linked to /guides, but I don't see the guides page being useless in the future as a separate entity from the profile?

**Comment by roryaronson** [comment]
I agree that it may be useful one day. Should we just have a stub `guides/index`?

**Comment by simonv3** [comment]
Maybe it makes sense to just redirect people to the profile for now? (that might be a routing thing, I'd have to look it up)

**Comment by roryaronson** [comment]
ok, Well I think I'm ready for an initial PR for my frontend work for the members page. There are a few things that need to happen which I'll outline in my PR, including rerouting `guides/index`

**Comment by simonv3** [comment]
Added in #617

**Comment by andru** [comment]
Slightly off topic general feedback but since this is closed maybe noone cares?

- Shouldn't all that delete account info only show once the button is clicked?  I'm feeling like `relax website, I'm not deleting anything, i just scrolled down here to see what's hiding down here.`

- Should users even be allowed to delete their guides? That seems like a weird question, but once they've published them they've released them to the community under a CC license. Afaik users don't get to delete their contributions to wikipedia because they changed their mind.  At the very least, perhaps they shouldn't have the idea put in their head by the delete account blurb?

The rest is awesome. Love the lock/globe for instant privacy feedback.

Props on your followers. You got connections.

**Comment by roryaronson** [comment]
Hey Andru, we definitely still care because there is always room for improvement ;)

Good suggestion about the delete account info. It shouldn't really be on the profile page, but on a separate page that thoroughly explains what happens to the data after account deletion, and offer a way to export member data too. On staging (Simon's implementation of all this) this is already the case. One scrolls down and presses a link to 'Manage Account Settings', where they can change their password, delete their account, etc.

Regarding deleting guides, I've opened up an issue to discuss that: #637
