### ISSUE TITLE
Integrate with farmOS

### ISSUE THREAD

**Issue by mstenta** [openfarmcc/OpenFarm#708]
http://farmos.org

I'm not sure how this would work, but I'm down for brainstorming! :-)

Maybe provide a way for OpenFarm to import data from farmOS? So you could share what you're working on with the OpenFarm community.

**Comment by roryaronson** [comment]
Hey @mstenta thanks for chiming in here!

The most immediate way I could see us collaborating is through the sharing of a crop database + crop icons. So for example, farmOS could use the same crop database as OpenFarm rather than creating/maintaining its own. This is what FarmBot is doing, and potentially some other projects.

**Comment by mstenta** [comment]
@roryaronson Agree 100%! I've already started talking with @simonv3, @andu, and others in these issues:

https://github.com/openfarmcc/Crops/issues/2
https://github.com/openfarmcc/Crops/issues/4

We're starting to put thoughts together for a standard data format here: 

https://github.com/openfarmcc/Crops/wiki/Crop-data-needs

Excited to see where it goes! :-)

**Comment by roryaronson** [comment]
I see! Just now catching up :eyes: 

I guess we can close this one then
