### ISSUE TITLE
Crop information covered by footer

### ISSUE THREAD

**Issue by itsrachelfish** [openfarmcc/OpenFarm#716]
The footer covers part of the content on any crop page when your screen screen is shorter than the content.  This is pretty easy to happen when a description is filled out, or if you're on a laptop with a smaller screen.

For example: https://openfarm.cc/en/crops/onion

![openfarm-footer-bug](https://cloud.githubusercontent.com/assets/1670549/13247428/c0316f20-d9d6-11e5-94fb-619355531c86.png)

It seems like this bug only happens when the page first loads. If you resize the window, the page is dynamically resized by javascript which fixes it. Oddly enough, if you disable javascript entirely the footer does not cover up the content either.

Tested in firefox and chrome

**Edit: It looks like this bug only happens when the description for a plant is longer than the number of guides it has.** The cherry tomato page has significantly more guides and this issue does not occur: https://openfarm.cc/en/crops/cherry-tomato

**Comment by roryaronson** [comment]
Good catch, and thanks for hopping into GitHub @itsrachelfish.

I think the way the page is coded now is that the scrolling height is determined by the right column. So if the left is longer, than it doesn't contribute to scrollable real estate.

**Comment by simonv3** [comment]
This footer has been a consistent headache. I don't know why it's so troublesome. Maybe I'll have to do a deepdive and fix it. (It's also a problem in guide creation).

**Comment by simonv3** [comment]
Okay, I think I figured out what's going wrong here. I think it'd be a fairly good opportunity for a newcomer to flex their Angular muscle:

The issue is that `.guide-results-container` [gets "equalized"](https://github.com/pineconellc/angular-foundation/issues/200) to be the same size as the crop container, but because Foundation doesn't play super nice alongside Angular (reflows don't happen based on new Angular content appearing) when the page loads crop data, that sizing is no longer valid. 

So, what I suggest doing is writing our own equalize directive. A good starting point is here:

https://github.com/pineconellc/angular-foundation/issues/200

You can then apply that directive to both the crop and the guide columns of the [crop/show.html.erb](https://github.com/openfarmcc/OpenFarm/blob/master/app/views/crops/show.html.erb) page.

**Comment by TanSA05** [comment]
@simonv3 Should this be labelled, "Angular"?

**Comment by simonv3** [comment]
@TanSA05 not only that, but I also think this issue is fixed. We can re-open if it re-appears.
