### ISSUE TITLE
Hide empty (draft) guides by default

### ISSUE THREAD

**Issue by CloCkWeRX** [openfarmcc/OpenFarm#805]
On production, a lot of people try out the site without realising that they are being encouraged to write up a guide.

#637 talks about not deleting *useful* guides, but the opposite scenario has happened.

This results in:
![image](https://cloud.githubusercontent.com/assets/365751/18512208/2bf42cca-7ac7-11e6-991c-7bab3ef6335b.png)

... which doesn't really showcase the point of openfarm.

Modelling a guide status or completeness (draft => published) would create a way to only show relevant guides more easily.

**Comment by simonv3** [comment]
We've actually discussed adding a `draft` boolean to guides. This would be super useful, and would mean guides only get shown if the user clicks on "Publish" at the end. 100% agreed.

**Comment by simonv3** [comment]
This is now implemented! 

Todo: send out an e-mail to members saying that drafts of guides are now possible. Encourage them to complete their guides.

**Comment by roryaronson** [comment]
Just tested this on staging:

1. Hit the "review" button
2. Successful redirect to my draft guide, with big banner on top (great job with that!)
3. Toast notification showed that I had successfully created a guide, which was a little confusing, because the banner tells me this is a draft, and the toast is telling me I've created the guide. The messages are just kind of conflicting. I suggest we remove the toast notification.
4. I hit the "Publish" button and the banner immediately dissappeared, but I wasn't sure if it successfully published. I suggest that this is where a toast should show (either successful publishing or error)
5. Go to check the search results, guide is not listed.
6. Went back to the guide and the banner had re-appeared. Clicked publish again and the same thing happened (banner disappears but it doesn't actually publish) This showed up in the console:

```
application-dfb1196….js:5 TypeError: Cannot read property 'image_url' of null
    at g (show-d14e067….js:1)
    at c.e.saveGuideChanges (show-d14e067….js:1)
    at t.$$ChildScope.$$ChildScope.e.publish (show-d14e067….js:1)
    at application-dfb1196….js:6
    at application-dfb1196….js:6
    at t.$$ChildScope.$$ChildScope.$eval (application-dfb1196….js:5)
    at t.$$ChildScope.$$ChildScope.$apply (application-dfb1196….js:5)
    at HTMLButtonElement.<anonymous> (application-dfb1196….js:6)
    at HTMLButtonElement.dispatch (application-dfb1196….js:2)
    at HTMLButtonElement.m.handle (application-dfb1196….js:2)
```

Here is the test guide: http://staging.openfarm.cc/en/guides/57e8a10cf3d809000300000e

**Comment by roryaronson** [comment]
A little update: The test guide I made originally did not have any images (not even a cover image). This seemed to be preventing it from publishing. Once I edited the guide and added a cover image, the publish button worked, the banner disappeared, and the guide showed up in search results.

**Comment by simonv3** [comment]
Okay, so I've just pushed a fix for this to staging. The issue was that I also implemented adding a featured image to the update-guide process. That broke because it now assumed that an image was always present when updating. Oops! Should really think about writing those front-end tests a bit more. 

The bug should be fixed. Remaining todo: 

* [ ] Make toast pop up in the right place. I suspect we should just remove the notification from the erb. controller and just do it on callback in the JavaScript.
