### ISSUE TITLE
Cannot 'add to garden' control on a guide in some circumstances

### ISSUE THREAD

**Issue by CloCkWeRX** [openfarmcc/OpenFarm#809]
![image](https://cloud.githubusercontent.com/assets/365751/18513185/9f0947f0-7acb-11e6-8852-fb4e5981f173.png)

It simply generates a JS error; which may or may not be related

```
application-422078f….js:15 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined
```

**Comment by simonv3** [comment]
Hmm, as I just mentioned on the other issue, users do automatically get a garden added on sign up. (a garden gets added if one doesn't already exist). I wonder if that's related.

**Comment by TheChirpyWitch** [comment]
This error was not present till some weeks ago. I am working to fix it by trying to find when this functionality was changed.

**Comment by simonv3** [comment]
I think the "getBoundingClientRect" error is a red herring, for what it's worth.

**Comment by TheChirpyWitch** [comment]
Yeah, I think so too. I googled the error and it doesn't make much semse. I will try reverting to old code. Let's see what happens.

**Comment by CloCkWeRX** [comment]
> getBoundingClientRect

Yeah, it cropped up in another area after I wrote this one up. 
I wasn't sure why it occurred and didn't show 'Your First Garden'; similar controls were visible later on - it mislead me into thinking there was no garden at all.

This one might be either a wontfix (as new users have a garden) or might be better to narrow in on just the getBoundingClientRect problem.

**Comment by TheChirpyWitch** [comment]
This issue is only occurring when we call _add_to_gardens.html from a crop's guide, not when we call it from the crop itself. Meaning that there is some error in the view or functionality for 'add-to-gardens'. So I just commented some HTML as in here:
`<div class="add-to-garden center">
          
        </div>`
And voila! It works. Still don't know why this was happening. My best guess is making the first div class 'add-to-garden' was somehow messing things up by rendering our addToGarden functionality.
