### ISSUE TITLE
Footer links a little wonky

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#837]
The saga continues...
![capture](https://cloud.githubusercontent.com/assets/5524043/19085714/2bb43774-8a20-11e6-80a9-65db725414b8.JPG)

**Comment by simonv3** [comment]
There might just not be enough space for all of them and we need to rethink the structure of it. 

What if we do 

| _About_ | _Contact_ | _Legal_ | 
---------|------------|--------
| F.A.Q. | Chat Room | Terms of Service |
| About us | Mailing List | Privacy |
| Blog | | Code of Conduct |
| Open Source | |

**Comment by roryaronson** [comment]
I like this ^^

Leaves us room to expand too :)

**Comment by AustinLMayes** [comment]
You could always evenly divide it between two rows.

**Comment by simonv3** [comment]
@AustinLMayes That's certainly another option. Maybe "contact-y" stuff on the first row, and more "legal" things on the second? 

So:

About, FAQ, Blog, Chat Room, Mailing List
Privacy, Terms of Service, Code of Conduct

**Comment by TanSA05** [comment]
I really like the first idea posted by @simonv3 simply because I've seen it on so many websites, and it looks really nice. (PFA screenshot of Kickstarter's footer)
![screenshot from 2016-10-05 03 48 31](https://cloud.githubusercontent.com/assets/9038802/19094661/d6fbc01e-8aae-11e6-95a3-f1bf7da72596.png)

Also, thanks for the label `hacktoberfest` ^_^ I can definitely try to take this one on (little apprehensive with the whole CSS thing with Hound)

**Comment by simonv3** [comment]
Aside: @TanSA05, feel free to add any `hactoberfest` labels to any issues you think make sense (eg if they are small, bite-size, etc), you've got the power on the repo!

I would recommend reading up on [flexbox for css](https://css-tricks.com/snippets/css/a-guide-to-flexbox/), I think that that makes the most sense here - especially when tackling responsiveness.
