### ISSUE TITLE
Remove ng-invalid red border styling on homepage search input

### ISSUE THREAD

**Issue by speizerj** [openfarmcc/OpenFarm#846]
<img width="427" alt="screenshot 2016-10-05 15 41 38" src="https://cloud.githubusercontent.com/assets/1063758/19134503/3c40c118-8b13-11e6-98cf-4a10344432a8.png">

**Comment by simonv3** [comment]
I noticed that this also shows up when adding crops to gardens:

![screenshot 2016-10-09 10 10 33](https://cloud.githubusercontent.com/assets/485583/19222593/a325bf12-8e08-11e6-94cf-cffb9d5527c1.png)

**Comment by TanSA05** [comment]
And it shows up when searching for a crop in the create guide page.
![screenshot from 2016-10-12 01 37 01](https://cloud.githubusercontent.com/assets/9038802/19286764/90fc374c-901c-11e6-961e-5e7475b64fbe.png)

**Comment by simonv3** [comment]
Everywhere! So what's wrong here is that our .ng-invalid rule in the CSS should probably only apply on _some_ inputs, rather than having a global rule. Thoughts?

**Comment by speizerj** [comment]
@simonv3 Agreed. How about we create a new class like `.input-invalid-notify` or something similar, and then the css rule would be:

`.input-invalid-notify.ng-invalid`

for the inputs we want to highlight with a red border when invalid. How's that sound?

**Comment by simonv3** [comment]
That sounds good to me.

**Comment by Katy310** [comment]
How do I get started on this issue?

**Comment by simonv3** [comment]
Hey @Katy310! How I would get started on this issue is by getting the app up and running and then adding a rule to the scss in this file:

https://github.com/openfarmcc/OpenFarm/blob/2a3052105758c918a17aea4cf4cf8697b4fc2e5c/app/assets/stylesheets/styles/ui/inputs/inputs.scss#L19

which would specifically overwrite the $alert-color for the home screen. 

Possibly something like: 

```
input#search_crop_name.ng-invalid {
  border: none;
}

**Comment by Katy310** [comment]
Yeah, sure.

**Comment by Katy310** [comment]
From my understanding, the invalid CSS should add to the input box only when the user tries to make an invalid query. Hence the .ng-invalid class should be added to the input boxes dynamically through javascript. Thoughts and advice?

Also, where should I look for the js code that governs the search boxes?

**Comment by simonv3** [comment]
@Katy310 .ng-invalid gets automatically added by Angular when a search box and form is invalid.

It's managed by the ng-form directive: https://docs.angularjs.org/api/ng/directive/form

Right now it's attaching the ng-invalid class because the input field is technically invalid. Should the blank input field be seen as invalid or not? It's possible to do a blank search, but it's not ideal (we just return the most popular crops and guides). So it depends!

I personally think your PR https://github.com/openfarmcc/OpenFarm/pull/871 is good! It would just be nice to follow our CSS style guide and not use #id tags.

**Comment by Katy310** [comment]
I've given it another shot. Any feedback?

**Comment by simonv3** [comment]
@Katy310 Awesome. It's now live. Thanks so much for your work on this!

https://openfarm.cc/

**Comment by nicholasedwards** [comment]
@Katy310 great job!
