### ISSUE TITLE
Create a form for contributors onboarding

### ISSUE THREAD

**Issue by sophiakc** [openfarmcc/OpenFarm#862]
Use of Google form to collect info from new contributors:
- name
- twitter info, Github
- background, skills 
- how many hours available / week
- how long willing to commit? max being 1 month, renewable?

**Comment by simonv3** [comment]
Does it make sense to gather that last bullet? Or put a cap on it? Hopefully people want to commit indefinite time!

But maybe it does make sense to say "how long into the future do you see yourself contributing to OpenFarm?" So that we can know how long of a timespan that makes sense to get involved with.

Maybe also "Why do you want to contribute?"

**Comment by sophiakc** [comment]
Here is the final version that could be added to the readme:
https://docs.google.com/forms/d/e/1FAIpQLSfsKUABGJSO3gSfDUrdXymxP-GipdTLxbxsmR2FyxGdblN1-w/viewform

@simonv3 It's more important to focus on quality and reliable contributions for short period of time, renewable, rather than diluted ones for unlimited timestamp.

Does anyone feel comfortable in answering this survey "as a contributor"?
