### ISSUE TITLE
Create a Matrix room?

### ISSUE THREAD

**Issue by alexgleason** [openfarmcc/OpenFarm#961]
Hi, I'd like to join the discussion, but I'd prefer not to use Slack because I don't accept their [privacy policy](https://slack.com/privacy-policy). Is there any interest in creating a Matrix room?

I'm particularly interested because I've just helped launch the first version of [GardenHub](https://gardenhub.io/), an open source (AGPL-licensed) application that connects community gardeners with pickers to improve food distribution in urban areas. We're in the early stages of this application; right now it only facilitates orders and picking, but we'd like to make it a centralized portal where people can discover local community gardens, join them, and discuss things within the app.

OpenFarm and GardenHub seem like a perfect match. I can imagine using the API to generate the list of crops used by GardenHub, and giving people advice about the crops in their plot, as well as letting people submit guides through GardenHub which end up stored by OpenFarm. Etc., etc. The possibilities are endless!

I'm available at [#gardenhub:matrix.org](https://riot.im/app/#/room/#gardenhub:matrix.org) if anyone wants to jump in there. Thanks!

P.S. I'm an anarchist communist vegan anti-copyright advocate; all our work on GardenHub is free as in freedom. GitHub is the only proprietary software/service I still use. :confused:

**Comment by roryaronson** [comment]
Hey Alex,

Thanks for hopping into the discussion here! While I applaud the desire to use as much free-as-in-freedom software as possible, especially for open-source projects, we've had issues in the past with discussion about our project becoming too fragmented across platforms (Github, email, Slack, Loomio, IRC, etc). At least at this time I don't think spreading our very limited community and attention to a new space would serve us well.

On the note of collaboration though, I think it makes a lot of sense for you to use the OpenFarm API to pull information into GardenHub so that you don't need to reinvent the wheel in that regard. That's exactly what we do with [the FarmBot web app](https://github.com/FarmBot/farmbot-web-app) and its worked very well. In fact, most of the detailed crop information you find on OpenFarm today has probably been contributed by FarmBot people, including the 300+ crop icons that are available for common garden veggies.
