### ISSUE TITLE
Icon exploitable for XSS purposes

### ISSUE THREAD

**Issue by avonwyss** [openfarmcc/OpenFarm#988]
I tried to upload an OpenEmoji icon and by mistake uploaded HTML data. The result was a broken crop edit page - it looks as if the content of the icon is passed through 1:1 without any check or sanity measure, which would in consequence allow for XSS attacks.

I was only able to fix the edit page by setting a breakpoint in the Angular parse method and manually delete the icon content on hitting the breakpoint...

**Comment by RickCarlino** [comment]
@avonwyss Indeed, you have spotted an XSS vector. We patched production (openfarm.cc) as soon as we saw your message (more on that later). **Thanks for bringing this to our attention!** In the future, **please contact us privately if you find a security issue**- it gives us time to deploy a patch and prevents bad actors from exploiting the vulnerability. Learn more about responsible disclosure [here](https://en.wikipedia.org/wiki/Responsible_disclosure).

This vector was previously identified (see my comment from 18 April [here](https://github.com/openfarmcc/OpenFarm/blob/5e5dd5e452a355e5b17978977b5cdee23b30d9e3/app/mutations/crops/create_crop.rb#L16-L22)), but it appears that the changes to the `#update` action never made it into master (the `#create` action was already patched).

# What Happened

We upgraded Rails to a new version earlier this year. After the upgrade, we had reason to believe that the [Rails HTML sanitizer](https://github.com/rails/rails-html-sanitizer) became more aggressive about sanitizing strings. Being more aggressive about string sanitization is a good thing, but it caused many SVG icons to break. In order to make icons work again, we needed to do raw string insertion of the SVG icon into the page.

For obvious reasons, it would no longer be safe to use untrusted strings as SVG crop icons. The long term solution, if we wished to allow for end-users to submit custom SVG icons, would be to implement a content security policy that disallows the use of `script` tags and non-whitelisted domains.

Unfortunately, the application had accumulated many inline `script` tags over the years which made this unfeasible. The risk of causing breakage to lesser-used parts of the app was simply too high. We decided on a less aggressive solution in the interim: disable SVG icon uploads by end users.

At that point in time, nearly all of the icons in the database were submitted by an artist commissioned by FarmBot, so we viewed it as a minimally invasive means of solving the problem. Furthermore, the fact that API consumers are using the crop icons in production (notably, in an educational setting), it was a safe decision to no longer allow uploads of SVG icons by end-users unless they were reviewed and manually uploaded by a member of the OpenFarm core team. This would also remove the risk of malicious users submitting not only XSS code, but also content that is offensive.

At some point, however, only the `create` endpoint was disabled, leaving the `update` endpoint unpatched.

# The Fix

At 8 AM Saturday (US Central Time), Github user @avonwyss reported discovery of the XSS vulnerability on the `#update` endpoint for crops. I was alerted to the matter by a FarmBot employee and immediately began investigating. When we determined that the vulnerability was substantiated, we performed an emergency patch deployment which is now running on the production instance of OpenFarm. As a preventative measure, we deleted all SVG icons that were created between April 18th and May 18th. **At this time, there is no evidence that this vulnerability has been used for malicious purposes.** If you have any information related to this incident, please email `security@farmbot.io` so that we may investigate the matter further.

# Sorry!

As stated previously, we do not have any evidence that this vulnerability was exploited for malicious use. We apologize to our end users for not seeing this sooner and **thank to @avonwyss for bringing it to our attention**.

**Comment by RickCarlino** [comment]
@avonwyss FarmBot offers a security bounty for substantiated production XSS vulnerabilities. Please contact me privately so that we may send it to you.
